

#ifndef __CONFIG_ZYNQ_PICOZED_FIREFLY_H
#define __CONFIG_ZYNQ_PICOZED_FIREFLY_H


#define CONFIG_ZYNQ_SDHCI0
#define CONFIG_ZYNQ_QSPI
#define CONFIG_ZYNQ_I2C0
#define CONFIG_ZYNQ_EEPROM
#define CONFIG_ENV_OFFSET 0x00380000
#define CONFIG_SPI_FLASH
#define CONFIG_SPI_FLASH_BAR

#include <configs/zynq_picozed.h>

#endif /* __CONFIG_ZYNQ_PICOZED_FIREFLY_H */
